version: "3.1"
services:
  backend:
    build: .
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgresql
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - cbar-net
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgresql
      POSTGRES_DBA: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cbar-net



networks:
  cbar-net:


volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data