server:
  port: 8088

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    enabled: true

cbar:
  url: https://www.cbar.az/currencies/
